version: '3.8'

# Mendefinisikan jaringan kustom agar kontainer bisa saling berkomunikasi
networks:
  msarch-net:
    driver: bridge

services:
  # Layanan untuk aplikasi Next.js Anda
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # GANTI DENGAN PUID DAN PGID DARI PENGGUNA NAS ANDA
        # Jalankan 'id <username>' via SSH di NAS untuk mendapatkannya.
        - PUID=1026
        - PGID=100
    container_name: msarch-app-prod
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Mengarahkan path database internal kontainer ke /app/data
      - DATABASE_PATH=/app/data
    volumes:
      # Map folder ./msarch-data di NAS ke /app/data di dalam kontainer.
      # Ini membuat data Anda (database, file proyek) tetap ada meskipun kontainer dihapus.
      - ./msarch-data:/app/data
      # Map folder avatar di NAS ke folder publik di dalam kontainer agar bisa diakses web.
      - ./msarch-data/uploads/avatars:/app/public/uploads/avatars
    networks:
      - msarch-net

  # Layanan untuk Cloudflare Tunnel
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: msarch-tunnel-connector
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    # Menambahkan layanan 'tunnel' ke jaringan yang sama
    networks:
      - msarch-net
